$devices = @(
    "ACPI Processor Aggregator",
    "ACPI Wake Alarm",
    "ACPI Thermal Zone",
    "Microsoft Windows Management Interface for ACPI",
    "Intel(R) Platform Monitoring Technology Device",
    "Direct memory access controller",
    "Virtual Device Enumerator",
    "System speaker",
    "UMBus Root Bus Enumerator",
    "Microsoft GS Wavetable Synth",
    "AMD PSP",
    "Base System Device",
    "Composite Bus Enumerator",
    "High Precision Event Timer",
    "Intel Management Engine",
    "Programmable interrupt controller",
    "Microsoft Kernel Debug Network Adapter",
    "Microsoft Virtual Drive Enumerator",
    "Microsoft RRAS Root Enumerator",
    "NDIS Virtual Network Adapter Enumerator",
    "Numeric Data Processor",
    "PCI Encryption/Decryption Controller",
    "PCI Memory Controller",
    "PCI standard ISA bridge",
    "System board",
    "System Timer",
    "Unknown Device",
    "WAN Miniport (IKEv2)",
    "WAN Miniport (IP)",
    "WAN Miniport (IPv6)",
    "WAN Miniport (L2TP)",
    "WAN Miniport (Network Monitor)",
    "WAN Miniport (PPPOE)",
    "WAN Miniport (PPTP)",
    "WAN Miniport (SSTP)",
    "ACPI\PNP0C0C\AA",
    "ACPI\PNP0C14\ASUSLEDCONTROLWMI",
    "ACPI\PNP0C14\ASUSMBSWINTERFACE",
    "ACPI\PNP0C14\AOD",
    "ACPI\PNP0C14\AWW",
    "SWD\RADIO{3DB5895D-CC28-44B3-AD3D-6F01A782B8D2}",
    "ROOT\SPACEPORT\0000",
    "NVIDIA Virtual Audio Device (Wave Extensible) (WDM)",
    "NvModuleTracker Device",
    "Remote Desktop Device Redirector Bus",
    "Microsoft Device Association Root Enumerator"
)

Get-PnpDevice -FriendlyName $devices -ErrorAction Ignore | Disable-PnpDevice -Confirm:$false -ErrorAction Ignore
