---
title: AppX
description: Remove unnecessary AppX packages
privilege: TrustedInstaller
actions:

  - !status: {status: 'Removing AppX packages...'}

  - !appx: {name: '*Microsoft.Windows.SecureAssessmentBrowser*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Windows.PeopleExperienceHost*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsCamera*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.Client.WebExperience*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WidgetsPlatformRuntime*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsAlarms*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsMaps*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.MicrosoftStickyNotes*', type: family, errorAction: Ignore}
  - !appx: {name: '*microsoft.windowscommunicationsapps*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.People*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.BingNews*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.BingSearch*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.BingWeather*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.MicrosoftSolitaireCollection*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsFeedbackHub*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.GetHelp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Getstarted*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Todos*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.PowerAutomateDesktop*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.549981C3F5F10*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftCorporationII.QuickAssist*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftCorporationII.MicrosoftFamily*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.ZuneMusic*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.ZuneVideo*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsSoundRecorder*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Windows.Photos*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsTerminal*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsTerminalPreview*', type: family, errorAction: Ignore}
  - !appx: {name: '*Clipchamp.Clipchamp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Whiteboard*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.MicrosoftTeamsforSurfaceHub*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftCorporationII.MailforSurfaceHub*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.MicrosoftPowerBIForWindows*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.SkypeApp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.MicrosoftOfficeHub*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Office.Excel*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Office.PowerPoint*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Office.Word*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Office.OneNote*', type: family, errorAction: Ignore}
  - !appx: {name: '*OutlookForWindows*', type: family, errorAction: Ignore}
  - !appx: {name: '*OutlookPWA*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Microsoft3DViewer*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Advertising*', type: family, errorAction: Ignore}
  - !appx: {name: '*MixedReality.Portal*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.MSPaint*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftTeams*', type: family, errorAction: Ignore}
  - !appx: {name: '*MSTeams*', type: family, errorAction: Ignore}
  - !appx: {name: '*DevHome*', type: family, errorAction: Ignore}
  - !appx: {name: '*WindowsBackup*', type: app, unregister: true, errorAction: Ignore}
  - !appx: {name: '*Flipgrid*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Xbox*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.GamingApp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.XboxApp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.YourPhone*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.CrossDevice*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Windows.Ai.Copilot*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.Client.AIX*', type: family, errorAction: Ignore}
  - !appx: {name: '*Disney*', type: family, errorAction: Ignore}
  - !appx: {name: '*Spotify*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsCalculator*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WindowsCalculator*', type: app, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Windows.DevHome*', type: family, errorAction: Ignore}
  - !appx: {name: '*Windows.Client.CBS*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Windows.Search*', type: family, errorAction: Ignore}
  - !appx: {name: '*SecHealthUI*', type: family, errorAction: Ignore}
  - !appx: {name: '*ScreenSketch*', type: family, errorAction: Ignore}
  - !appx: {name: '*Cortana*', type: family, errorAction: Ignore}
  - !appx: {name: '*Copilot*', type: family, errorAction: Ignore}
  - !appx: {name: '*Widget*', type: family, errorAction: Ignore}
  - !appx: {name: '*WebExperience*', type: family, errorAction: Ignore}
  - !appx: {name: '*AI.*', type: family, errorAction: Ignore}
  - !appx: {name: '*AIChat*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.MixedReality*', type: family, errorAction: Ignore}
  - !appx: {name: '*NcsiUwpApp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.AVCEncoderVideoExtension*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.AV1VideoExtension*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.UndockedDevKit*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.MPEG2VideoExtension*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.ApplicationCompatibilityEnhancements*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.HEIFImageExtension*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.HEVCVideoExtension*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.VP9VideoExtensions*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WebpImageExtension*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.WebMediaExtensions*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.RawImageExtension*', type: family, errorAction: Ignore}
  - !appx: {name: '*Edge.GameAssist*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.LKG.AccountsService*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.LKG.RulesEngine*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.LKG.TwinSxS*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.LKG.Search*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.LKG.DesktopSpotlight*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.LKG.IrisService*', type: family, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.LKG.SpeechRuntime*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Windows.AugLoop.CBS*', type: family, errorAction: Ignore}
  - !appx: {name: '*ContentDeliveryManager*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.ECApp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Windows.CBSPreview*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Lockapp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.BioEnrollment*', type: family, errorAction: Ignore}
  - !appx: {name: '*c5e2524a-ea46-4f67-841f-6a9465d9d515*', type: family, errorAction: Ignore}
  - !appx: {name: '*F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Windows.AssignedAccessLockApp*', type: family, errorAction: Ignore}
  - !appx: {name: '*NarratorQuickStart*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.AsyncTextService*', type: family, errorAction: Ignore}
  - !appx: {name: '*XGpuEjectDialog*', type: family, errorAction: Ignore}
  - !appx: {name: '*ParentalControls*', type: family, errorAction: Ignore}
  - !appx: {name: '*Microsoft.Windows.CallingShellApp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Livtop*', type: family, errorAction: Ignore}
  - !appx: {name: '*InpApp*', type: family, errorAction: Ignore}
  - !appx: {name: '*Speion*', type: family, errorAction: Ignore}
  - !appx: {name: '*Voiess*', type: family, errorAction: Ignore}
  - !appx: {name: '*Filons*', type: family, errorAction: Ignore}
  - !appx: {name: '*CortanaUI*', type: app, errorAction: Ignore}
  - !appx: {name: '*CortanaUIFullTrustApp*', type: app, errorAction: Ignore}
  - !appx: {name: '*DesktopSpotlight*', type: app, errorAction: Ignore}
  - !appx: {name: '*IrisService*', type: app, errorAction: Ignore}
  - !appx: {name: '*CopilotNudges*', type: app, errorAction: Ignore}
  - !appx: {name: '*CrossDeviceResume*', type: app, errorAction: Ignore}
  - !appx: {name: '*FamilyValueProp*', type: app, errorAction: Ignore}
  - !appx: {name: '*PackageMetadata*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.AppListBackup*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.DesktopStickerEditor*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.DesktopVisual*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.LiveCaptionsDesktop*', type: app, errorAction: Ignore}
  - !appx: {name: '*LogonWebHost*', type: app, errorAction: Ignore}
  - !appx: {name: '*VisualAssist*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.FeatureDiscoverability*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.MicrosoftGraphRecentItemsManager*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.PersonaCardManager*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.RulesEngine*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.WindowsMigration*', type: app, errorAction: Ignore}
  - !appx: {name: '*MiniSearchUI*', type: app, errorAction: Ignore}
  - !appx: {name: '*FESearchUI*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.SpeechRecognizerExtension*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.TwinSxS*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.SpeechSynthesizerExtension*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.ValueBanner*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.WindowsPeopleExperience*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.ExperienceExtensions*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.WsxPackManager*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.BackupBanner*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.VoiceAccessHost*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.VoiceAccessPlugin*', type: app, errorAction: Ignore}
  - !appx: {name: '*CrossDeviceResumeApp*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.DragTray*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.LockCanvas*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.WidgetDataModel*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.WidgetPicker*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.WidgetViewUWP*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.WidgetViewWinUI3*', type: app, errorAction: Ignore}
  - !appx: {name: '*Global.wsw*', type: app, errorAction: Ignore}
  - !appx: {name: '*MicrosoftWindows.Client.CoreAI*', type: app, errorAction: Ignore}
  - !appx: {name: '*DesktopStickerEditorCentennial*', type: app, errorAction: Ignore}

  # BLOCK REINSTALL - Deprovisioned keys
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.OneDrive_8wekyb3d8bbwe', operation: add, errorAction: Ignore}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\microsoft.microsoftskydrive_8wekyb3d8bbwe', operation: add, errorAction: Ignore}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.SkyDrive_8wekyb3d8bbwe', operation: add, errorAction: Ignore}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.OutlookForWindows_8wekyb3d8bbwe', operation: add, errorAction: Ignore}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MSPaint_8wekyb3d8bbwe', operation: add, errorAction: Ignore}
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.Windows.Photos_8wekyb3d8bbwe', operation: add, errorAction: Ignore}

  # Clear AppX caches
  - !appx: {operation: clearCache, name: '*Client.CBS*', errorAction: Ignore}
  - !appx: {operation: clearCache, name: '*StartMenuExperienceHost*', errorAction: Ignore}
  - !appx: {operation: clearCache, name: '*Windows.Search*', errorAction: Ignore}
  - !appx: {operation: clearCache, name: '*TCUI*', errorAction: Ignore}
